### ISSUE TITLE
Breaks when testing.elasticsearch is installed into the same environment

### ISSUE THREAD

**Issue by svenstaro** [tk0miya/testing.redis#2]
So I'm reporting this on both projects because I don't know which one is the one that causes this issue. I originally reported [this](https://github.com/jong/testing.elasticsearch/issues/13). It says:

> If testing.elasticsearch and testing.redis are installed into the same environment, this happens when trying to launch python:
> 
> KeyError: 'testing'
> 
> This is python 3.5.

**Comment by tk0miya** [comment]
Same as https://github.com/tk0miya/testing.common.database/issues/2.

**Comment by svenstaro** [comment]
Oh awesome, will just use testing.elasticsearch2 then. :P
